services:
  neo4jdb:
    image: neo4j:latest
    container_name: neo4jdb
    restart: unless-stopped
    volumes: 
      - neo4j_conf:/conf
      - neo4j_data:/data
      - neo4j_import:/import
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_server_memory_heap_max__size=1G
    networks:
      - neo4j_network
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7474
      - 7687

volumes:
  neo4j_conf:
  neo4j_data:
  neo4j_import:
  neo4j_logs:
  neo4j_plugins:

networks:
  neo4j_network:
    driver: bridge
